---
- name: Set up Git repository with token authentication
  hosts: all
  tasks:
    - name: Ensure the repository folder exists
      win_file:
        path: C:\test_ansible
        state: directory

    - name: Configure Git user name
      win_command: git config --global user.name "nazwa_użytkownika"
      args:
        chdir: C:\test_ansible

    - name: Configure Git user email
      win_command: git config --global user.email "email"
      args:
        chdir: C:\test_ansible

    - name: Configure Git credential helper to store
      win_command: git config --global credential.helper store
      args:
        chdir: C:\test_ansible

    - name: Add GitHub credentials
      win_shell: |
        echo https://nazwa_użytkownika:token@github.com > C:/Users/{{ ansible_user }}/.git-credentials
      args:
        chdir: C:\test_ansible

    - name: Initialize the Git repository
      win_command: git init
      args:
        chdir: C:\test_ansible

    - name: Add README.md file with dynamic content
      win_shell: |
        echo "# test_ansible $(date)" > README.md
      args:
        chdir: C:\test_ansible

    - name: Stage README.md
      win_command: git add README.md
      args:
        chdir: C:\test_ansible

    - name: Check git status
      win_command: git status
      args:
        chdir: C:\test_ansible

    - name: Commit changes (allow empty commit if no changes)
      win_command: git commit -m "first commit" --allow-empty
      args:
        chdir: C:\test_ansible

    - name: Set default branch to main
      win_command: git branch -M main
      args:
        chdir: C:\test_ansible

    - name: Add remote repository
      win_command: git remote add origin link do repo
      args:
        chdir: C:\test_ansible

    - name: Disable Git credential manager (optional)
      win_command: git config --global --unset credential.helper
      args:
        chdir: C:\test_ansible

    - name: Push changes to remote repository
      win_command: git push -u https:/nazwa_użytkownika:token@github.com/nazwa_użytkownika/nazwa_repo.git main
      args:
        chdir: C:\test_ansible
